### ISSUE TITLE
Base64 encoding

### ISSUE THREAD

**Issue by tacomanator** [LordZardeck/PAW-Auth0TokenDynamicValue#3]
As of sometime last year they are no longer base64 encoding secrets, which is causing this extension not to work for recently created apps.

**Comment by LordZardeck** [comment]
Yeah, I remember seeing that. If you have an idea on the fix for this, create a PR and i'll merge it it.

**Comment by subdigital** [comment]
What's the process for getting Paw to refresh the extension library to include this latest version? I made a custom plugin out of this and it works great. If you install it fresh from Paw it gets the old version.

**Comment by LordZardeck** [comment]
@subdigital I'm confused on what you are asking? Are you asking for the latest version of THIS plugin to show up in paw, or for your custom plugin to show up?

**Comment by subdigital** [comment]
This plugin.

**Comment by LordZardeck** [comment]
It probably uses git tags (releases) to determine what to load, lemme add one real quick

**Comment by LordZardeck** [comment]
@subdigital released. Also, for the future, please create a new issue unless the issue relates to the fix/feature of the issue. Thank you!
