### ISSUE TITLE
must issuer have trailing slash?

### ISSUE THREAD

**Issue by tacomanator** [LordZardeck/PAW-Auth0TokenDynamicValue#5]
Was going to submit PR to add trailing slash to issuer if not present, but I tested without and it worked fine. Are you sure that it's needed (as stated in README)?

**Comment by LordZardeck** [comment]
@tacomanator at the time I wrote this, it seemed to fail, but Auth0 has gone through many changes that I haven't gotten to test. What was the test case you used to verify that it's not needed?

**Comment by tacomanator** [comment]
I just tested an authenticated API call with and without the trailing slash, and both worked. I use `koa-jwt` which uses `jsonwebtoken`.

In any case, the token returned by Auth0 does include the trailing slash so probably better safe than sorry.
